# Generated by Django 4.1.1 on 2022-10-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_comment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="user_rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment", name="rating", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post", name="rating", field=models.IntegerField(default=0),
        ),
    ]
